//ACCOUNTS HANDLER
export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'

//WEBTONS HANDLER
export const GET_WEBTOONS = 'GET_WEBTOONS'
export const GET_RECENT = 'GET_RECENT'
export const GET_POPULARS = 'GET_POPULARS'

//EPISODES HANDLER
export const GET_EPISODES = 'GET_EPISODES'
export const ADD_EPISODE = 'ADD_EPISODE'
export const UPDATE_EPISODE = 'UPDATE_EPISODE'
export const DELETE_EPISODE = 'DELETE_EPISODE'

//DETAIL EPISODES HANDLER
export const GET_DETAIL_EPISODES = 'GET_DETAIL_EPISODE'
export const ADD_DETAIL_EPISODE = 'ADD_DETAIL_EPISODE'
export const DELETE_DETAIL_EPISODE = 'DELETE_DETAIL_EPISODE'

//USER HANDLER
export const UPDATE_USER = 'UPDATE_USER'
export const GET_FAVORITES = 'GET_FAVORITES'
export const ADD_FAVORITE = 'ADD_FAVORITE'
export const DELETE_FAVORITE = 'DELETE_FAVORITE'
export const STORE_DATA = 'STORE_DATA'